framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: topic
                    queues:
                        auth_messages:
                            binding_keys:
                                - 'auth.user_registered'
                                - 'auth.user_logged_in'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\UserRegistered': async
            'App\Message\UserLoggedIn': async
