api_auth_register:
    path: /register
    controller: App\Controller\Api\RegisterController::register
    methods: [POST]

api_auth_login:
    path: /login
    controller: App\Controller\Api\LoginController::login
    methods: [POST]

api_auth_logout:
    path: /logout
    controller: App\Controller\Api\LogoutController::logout
    methods: [POST]

api_auth_refresh:
    path: /refresh
    controller: App\Controller\Api\RefreshTokenController::refresh
    methods: [POST]

api_auth_profile:
    path: /profile
    controller: App\Controller\Api\ProfileController::profile
    methods: [GET]
